(let ((buffer (get-buffer-create "*slime-helpful*")))
  (with-current-buffer buffer
    (insert "hello")
    (insert "\n")
    (insert (propertize "Function" 'face 'bold))
    (insert "\n")
    (insert (propertize "Italic" 'face 'italic))
    (insert (propertize "Italic" 'face 'variable-pitch))
    (display-buffer buffer)))

(slime-eval `(swank::read-elisp-symbol-info 'alexandria:flatten))

(defun render-parsed-docstring (docstring)
  (dolist (word docstring)
    (cond
     ((stringp word) (insert word))
     ((and (listp word) (eql (first word) :arg))
      (insert (propertize (second word) 'face 'highlight)))
     ((and (listp word) (eql (first word) :fn))
      (insert (propertize (second word) 'face 'link)))
     ((and (listp word) (eql (first word) :key))
      (insert (propertize (second word) 'face 'underline)))
     ((and (listp word) (eql (first word) :var))
      (insert (propertize (second word) 'face 'highlight)))
     (t (error "Don't know how to render")))))

(defun sh--propertize-heading (text)
  (propertize text 'face 'bold))

(let ((symbol-info (slime-eval `(swank::read-elisp-symbol-info 'split-sequence:split-sequence))))
  (let ((buffer (get-buffer-create "*slime-helpful*")))
    (with-current-buffer buffer
      (insert (sh--propertize-heading (cdr (assoc :name symbol-info))))
      (newline 2)
      (insert (format "This is a FUNCTION in package %s" (cdr (assoc :package symbol-info))))
      (newline 2)
      (insert (sh--propertize-heading "Signature"))
      (newline)
      (insert (cdr (assoc :args symbol-info)))
      (newline 2)
      (render-parsed-docstring (cdr (assoc :parsed-documentation symbol-info)))
      (display-buffer buffer))))
